# Uncomment this if your project is hosted on GitHub:
github_url = "https://github.com/typst-tools4tpst/"

[version]
current = "0.4.1"

# Example of a semver regexp.
# Make sure this matches current_version before
# using tbump
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

# uncomment to also update typst.toml
# [[file]]
# src = "typst.toml"
# search = 'version = "{current_version}"'

[[file]]
src = "README.md"
search = '\(v{current_version}\)'
[[file]]
src = "README.md"
search = "t4t:{current_version}"

[[before_commit]]
name = "compile manual"
cmd = "just doc"
